version: '3.8'

services:
  generic-service:
    image: makaminski1337/duke:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_EXECUTABLE=duke
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 10s
      retries: 3