services:
  service:
    image: makaminski1337/duke:latest
    environment:
      INFISICAL_CLIENT_ID: "${infisical_client_id}"
      INFISICAL_SECRET: "${infisical_secrets}"
      INFISICAL_PROJECT_ID: "${infisical_project_id}"
      service_name: "${service_name}"
    ports:
      - "8080:8080"
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 10s
      retries: 3