name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service name for the Docker image'
        required: true
        default: duke
      docker_username:
        description: 'Docker Hub username'
        required: true
      docker_password:
        description: 'Docker Hub password'
        required: true
      infisical_client_id:
        description: 'Infisical Client ID'
        required: true
      infisical_secret:
        description: 'Infisical Client Secret'
        required: true
      infiscal_project_id:
        description: 'Infisical Project ID'
        required: true
      digital_ocean_token:
        description: 'Digital Ocean token'
        required: true
      host:
        description: 'Manager IP address'
        required: true
      password:
        description: 'Root password'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Knowvus/.github/actions/build-and-push@main
        with:
          service_name: ${{ github.event.inputs.service_name || 'duke' }}
          docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: SSH into Droplet and Deploy
        env:
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_SECRET: ${{ secrets.INFISICAL_SECRET }}
          INFISICAL_PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DO_DUKE_IP }}
          username: root
          password: ${{ secrets.DUKE_ROOT_PASSWORD }}
          script: |
            mkdir -p /root/deployment_directory
            curl -o /root/deployment_directory/docker-compose.yaml https://raw.githubusercontent.com/Knowvus/duke/main/docker-compose.yaml
            curl -o /root/deployment_directory/Dockerfile https://raw.githubusercontent.com/Knowvus/duke/main/Dockerfile
        
            # Navigate to the deployment directory
            cd /root/deployment_directory

            # Create a temporary .env file with the secrets dynamically
            echo "INFISICAL_CLIENT_ID=${INFISICAL_CLIENT_ID}" > .env
            echo "INFISICAL_SECRET=${INFISICAL_SECRET}" >> .env
            echo "INFISICAL_PROJECT_ID=${INFISICAL_PROJECT_ID}" >> .env

            # Deploy using Docker Compose
            docker-compose --env-file .env -f docker-compose.yaml pull
            docker-compose --env-file .env -f docker-compose.yaml up -d
