name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service name for the Docker image'
        required: true
        default: duke
      docker_username:
        description: 'Docker Hub username'
        required: true
      docker_password:
        description: 'Docker Hub password'
        required: true
      infisical_client_id:
        description: 'Infisical Client ID'
        required: true
      infisical_secret:
        description: 'Infisical Client Secret'
        required: true
      project_id:
        description: 'Infisical Project ID'
        required: true
      digital_ocean_token:
        description: 'Digital Ocean token'
        required: true
      host:
        description: 'Manager IP address'
        required: true
      password:
        description: 'Root password'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Knowvus/.github/actions/build-and-push@main
        with:
          service_name: ${{ github.event.inputs.service_name || 'duke' }}
          docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main repository (to get docker-compose.yml)
        uses: actions/checkout@v2
        with:
          repository: your-org/your-main-repo
          path: main-repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Deploy Application to Droplet
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          SERVICE_NAME: ${{ github.event.inputs.service_name || 'duke' }}
          DO_DUKE_IP: ${{ secrets.DO_DUKE_IP }}
        run: |
          # Pull the latest Docker image
          echo "Pulling the latest Docker image..."
          docker pull "$DOCKER_HUB_USERNAME/$SERVICE_NAME:latest"

          # Initialize Docker Swarm
          echo "Initializing Docker Swarm..."
          docker swarm init --advertise-addr $DO_DUKE_IP || echo "Docker Swarm already initialized."

          # Deploy using Docker Compose
          echo "Deploying with Docker Compose..."
          cd main-repo/deploy  # Adjust this path if docker-compose.yml is located elsewhere
          docker-compose pull
          docker-compose up -d
