name: Deploy Docker Swarm Manager (Duke)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Duke as Docker Swarm Manager
        uses: Knowvus/.github/actions/deploy-service/manager@main
        with:
          docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker_image: ${{ secrets.DOCKER_HUB_USERNAME }}/duke:${{ github.sha }}
          infisical_client_id: ${{ secrets.INFISICAL_MACHINE_IDENTITY_CLIENT_ID }}
          infisical_client_secret: ${{ secrets.INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET }}
          project_id: ${{ secrets.PROJECT_ID }}
