name: Deploy Docker Swarm Manager Service

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash  # Set the default shell for all run steps

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Knowvus/.github/actions/build-and-push@main  # Call the build script from external repo
        with:
          service_name: ${{ secrets.DOCKER_HUB_USERNAME }}/duke:latest  # Pass the service name as a secret or input
          docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the deploy job waits for the build to finish
    steps:
      - name: Deploy Service as Docker Swarm Member
        uses: Knowvus/.github/actions/deploy-service/member@main  # Call the deploy script from external repo
        with:
          docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker_image: ${{ secrets.DOCKER_HUB_USERNAME }}/duke:latest
          infisical_client_id: ${{ secrets.INFISICAL_MACHINE_IDENTITY_CLIENT_ID }}
          infisical_client_secret: ${{ secrets.INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET }}
          manager_ip: ${{ secrets.DO_DUKE_IP }}
          project_id: ${{ secrets.PROJECT_ID }}
