name: Deploy Docker Swarm Manager Service

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Knowvus/.github/actions/build-and-push@main
        with:
          service_name: duke
          docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Service as Docker Swarm Manager
        uses: Knowvus/.github/actions/deploy-service/manager@main
        with:
          service_name: duke
          docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          digital_ocean_token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          manager_ip: ${{ secrets.DO_DUKE_IP }}
          manager_root_password: ${{ secrets.DUKE_ROOT_PASSWORD }}
          infisical_client_id: ${{ secrets.INFISICAL_CLIENT_ID }}
          infisical_secrets: ${{ secrets.INFISICAL_SECRETS }}
          infisical_project_id: ${{ secrets.INFISICAL_PROJECT_ID }}