name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  # Job for building the Rust application
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true

      - name: Install Infisical CLI
        run: |
          curl -L -o infisical_0.28.4_linux_amd64.tar.gz https://github.com/infisical/infisical/releases/download/infisical-cli/v0.28.4/infisical_0.28.4_linux_amd64.tar.gz
          tar -xzf infisical_0.28.4_linux_amd64.tar.gz
          chmod +x infisical
          sudo mv infisical /usr/local/bin/infisical

      - name: Login to Infisical
        run: |
          INFISICAL_TOKEN=$(infisical login --method=universal-auth --client-id=$INFISICAL_CLIENT_ID --client-secret=$INFISICAL_CLIENT_SECRET --plain --silent)
          echo "INFISICAL_TOKEN=${INFISICAL_TOKEN}" >> $GITHUB_ENV
        env:
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}

      - name: Build Docker Image
        run: |
          docker build --cache-from ${{ secrets.DOCKER_HUB_USERNAME }}/app:cache --tag ${{ secrets.DOCKER_HUB_USERNAME }}/app:${{ github.sha }} .
        env:
          INFISICAL_TOKEN: ${{ env.INFISICAL_TOKEN }}

      - name: Push Docker Cache
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/app:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/app:cache
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/app:cache

  # Job for deploying the built image
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/app:${{ github.sha }}

      - name: Deploy to DigitalOcean Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITALOCEAN_DROPLET_IP }} << EOF
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/app:${{ github.sha }}
          docker stop app || true
          docker rm app || true
          docker run -d -p 8080:8080 --name app ${{ secrets.DOCKER_HUB_USERNAME }}/app:${{ github.sha }}
          EOF
        env:
          INFISICAL_TOKEN: ${{ env.INFISICAL_TOKEN }}
